/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.DialogFile {
    export class AdornBuyUI extends Dialog {
		public bg:Laya.Image;
		public box_info:Laya.Box;
		public img_icon:Laya.Image;
		public txt_name:Laya.Label;
		public txt_des:Laya.Label;
		public html_energyLack:Laya.HTMLDivElement;
		public html_centerTip:Laya.HTMLDivElement;
		public box_fashionBuy:Laya.Box;
		public txt_discountTime:Laya.Label;
		public btn_left:Laya.Button;
		public btn_right:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("DialogFile/AdornBuy");
        }
    }
    REG("ui.DialogFile.AdornBuyUI",AdornBuyUI);
    export class PopUpUI extends Dialog {
		public txt_popUp:Laya.Label;
		public txt_html:Laya.HTMLDivElement;
		public close_btn:Laya.Image;
		public close_txt:Laya.Label;
		public ensure_btn:Laya.Image;
		public ensure_txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("DialogFile/PopUp");
        }
    }
    REG("ui.DialogFile.PopUpUI",PopUpUI);
}
export module ui.EffectFile {
    export class loading_PenUI extends Laya.EffectAnimation {
		public ani1:Laya.FrameAnimation;
        public static  uiView:any ={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":560,"x":0,"skin":"ui_loading/img_loading_pen.png","rotation":-8,"anchorY":1},"compId":3}],"animations":[{"nodes":[{"target":3,"keyframes":{"y":[{"value":560,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":0},{"value":545,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":25},{"value":560,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":50}],"skin":[{"value":"ui_loading/img_loading_pen.png","tweenMethod":"linearNone","tween":false,"target":3,"key":"skin","index":0}],"rotation":[{"value":-8,"tweenMethod":"linearNone","tween":true,"target":3,"key":"rotation","index":0},{"value":0,"tweenMethod":"linearNone","tween":true,"target":3,"key":"rotation","index":25},{"value":-8,"tweenMethod":"linearNone","tween":true,"target":3,"key":"rotation","index":50}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["ui_loading/img_loading_pen.png"],"loadList3D":[]};
        constructor(){ super();this.effectData =ui.EffectFile.loading_PenUI.uiView;}
    }
    REG("ui.EffectFile.loading_PenUI",loading_PenUI);
}
export module ui.ViewFile {
    export class FashionShopUI extends View {
		public img_bg:Laya.Image;
		public btn_back:Laya.Image;
		public txt_comfort:Laya.Label;
		public txt_energy:Laya.Label;
		public box_center:Laya.Box;
		public role_root:Laya.Box;
		public txt_itemName:Laya.Label;
		public txt_itemDes:Laya.Label;
		public txt_comfyValue:Laya.Label;
		public btn_use:Laya.Button;
		public btn_save:Laya.Button;
		public btn_itemBuy:Laya.Button;
		public btn_All:Laya.Image;
		public btn_hair:Laya.Image;
		public btn_clothes:Laya.Image;
		public btn_shose:Laya.Image;
		public btn_face:Laya.Image;
		public list_panel:Laya.List;
		public img_SettingBg:Laya.Image;
		public btn_Setting:Laya.Image;
		public img_cutBg:Laya.Image;
		public btn_cut:Laya.Image;
		public txt_cut:Laya.Label;
		public txt_cutBg:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ViewFile/FashionShop");
        }
    }
    REG("ui.ViewFile.FashionShopUI",FashionShopUI);
    export class GuideUI extends View {
		public listPanel:Laya.Panel;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ViewFile/Guide");
        }
    }
    REG("ui.ViewFile.GuideUI",GuideUI);
    export class LoadingUI extends View {
		public write:Laya.FrameAnimation;
		public img_progressMask:Laya.Image;
		public eff_pen:ui.EffectFile.loading_PenUI;
		public txt_value:Laya.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ViewFile/Loading");
        }
    }
    REG("ui.ViewFile.LoadingUI",LoadingUI);
}