/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.DialogFile {
    export class PopUpUI extends Dialog {
		public txt_popUp:Laya.Label;
		public txt_html:Laya.HTMLDivElement;
		public close_btn:Laya.Image;
		public close_txt:Laya.Label;
		public ensure_btn:Laya.Image;
		public ensure_txt:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("DialogFile/PopUp");
        }
    }
    REG("ui.DialogFile.PopUpUI",PopUpUI);
}
export module ui.EffectFile {
    export class loading_PenUI extends Laya.EffectAnimation {
		public ani1:Laya.FrameAnimation;
        public static  uiView:any ={"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":560,"x":0,"skin":"ui_loading/img_loading_pen.png","rotation":-8,"anchorY":1},"compId":3}],"animations":[{"nodes":[{"target":3,"keyframes":{"y":[{"value":560,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":0},{"value":545,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":25},{"value":560,"tweenMethod":"linearNone","tween":true,"target":3,"key":"y","index":50}],"skin":[{"value":"ui_loading/img_loading_pen.png","tweenMethod":"linearNone","tween":false,"target":3,"key":"skin","index":0}],"rotation":[{"value":-8,"tweenMethod":"linearNone","tween":true,"target":3,"key":"rotation","index":0},{"value":0,"tweenMethod":"linearNone","tween":true,"target":3,"key":"rotation","index":25},{"value":-8,"tweenMethod":"linearNone","tween":true,"target":3,"key":"rotation","index":50}]}}],"name":"ani1","id":1,"frameRate":24,"action":0}],"loadList":["ui_loading/img_loading_pen.png"],"loadList3D":[]};
        constructor(){ super();this.effectData =ui.EffectFile.loading_PenUI.uiView;}
    }
    REG("ui.EffectFile.loading_PenUI",loading_PenUI);
}
export module ui.ViewFile {
    export class LoadingUI extends View {
		public write:Laya.FrameAnimation;
		public img_progressMask:Laya.Image;
		public eff_pen:ui.EffectFile.loading_PenUI;
		public txt_value:Laya.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ViewFile/Loading");
        }
    }
    REG("ui.ViewFile.LoadingUI",LoadingUI);
    export class ScreenShotUIUI extends View {
		public txt_time:Laya.Label;
		public img_bg:Laya.Image;
		public role_root:Laya.Box;
		public img_hair:Laya.Image;
		public img_clothes:Laya.Image;
		public img_shoes:Laya.Image;
		public img_face:Laya.Image;
		public btn_start:Laya.Button;
		public btn_stop:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ViewFile/ScreenShotUI");
        }
    }
    REG("ui.ViewFile.ScreenShotUIUI",ScreenShotUIUI);
}