/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import PopUp from "./View/dialog/PopUp"
import ButtonEff from "./Script/ButtonEff"
import LoadingUI from "./View/view/LoadingUI"
import ScreenShotUI from "./View/view/ScreenShotUI"
import Role from "./Prefab/Role"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="ViewFile/Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("View/dialog/PopUp.ts",PopUp);
        reg("Script/ButtonEff.ts",ButtonEff);
        reg("View/view/LoadingUI.ts",LoadingUI);
        reg("View/view/ScreenShotUI.ts",ScreenShotUI);
        reg("Prefab/Role.ts",Role);
    }
}
GameConfig.init();